INSERT INTO user_favorite_movies (user_id, movie_id) VALUES
((SELECT id FROM users WHERE username = 'john_doe'), (SELECT id FROM movies WHERE title = 'Inception')),
((SELECT id FROM users WHERE username = 'john_doe'), (SELECT id FROM movies WHERE title = 'The Dark Knight')),
((SELECT id FROM users WHERE username = 'john_doe'), (SELECT id FROM movies WHERE title = 'Avatar')),
((SELECT id FROM users WHERE username = 'jane_smith'), (SELECT id FROM movies WHERE title = 'Titanic')),
((SELECT id FROM users WHERE username = 'jane_smith'), (SELECT id FROM movies WHERE title = 'Interstellar')),
((SELECT id FROM users WHERE username = 'jane_smith'), (SELECT id FROM movies WHERE title = 'Pulp Fiction')),
((SELECT id FROM users WHERE username = 'alice_johnson'), (SELECT id FROM movies WHERE title = 'Jurassic Park')),
((SELECT id FROM users WHERE username = 'alice_johnson'), (SELECT id FROM movies WHERE title = 'Saving Private Ryan')),
((SELECT id FROM users WHERE username = 'alice_johnson'), (SELECT id FROM movies WHERE title = 'The Wolf of Wall Street')),
((SELECT id FROM users WHERE username = 'bob_brown'), (SELECT id FROM movies WHERE title = 'Goodfellas')),
((SELECT id FROM users WHERE username = 'bob_brown'), (SELECT id FROM movies WHERE title = 'Django Unchained')),
((SELECT id FROM users WHERE username = 'bob_brown'), (SELECT id FROM movies WHERE title = 'The Irishman')),
((SELECT id FROM users WHERE username = 'carol_davis'), (SELECT id FROM movies WHERE title = 'Kill Bill: Vol. 1')),
((SELECT id FROM users WHERE username = 'carol_davis'), (SELECT id FROM movies WHERE title = 'E.T. the Extra-Terrestrial')),
((SELECT id FROM users WHERE username = 'carol_davis'), (SELECT id FROM movies WHERE title = 'Terminator 2: Judgment Day')),
((SELECT id FROM users WHERE username = 'daniel_miller'), (SELECT id FROM movies WHERE title = 'Inception')),
((SELECT id FROM users WHERE username = 'daniel_miller'), (SELECT id FROM movies WHERE title = 'The Dark Knight')),
((SELECT id FROM users WHERE username = 'daniel_miller'), (SELECT id FROM movies WHERE title = 'Avatar')),
((SELECT id FROM users WHERE username = 'emma_wilson'), (SELECT id FROM movies WHERE title = 'Titanic')),
((SELECT id FROM users WHERE username = 'emma_wilson'), (SELECT id FROM movies WHERE title = 'Interstellar')),
((SELECT id FROM users WHERE username = 'emma_wilson'), (SELECT id FROM movies WHERE title = 'Pulp Fiction')),
((SELECT id FROM users WHERE username = 'frank_thompson'), (SELECT id FROM movies WHERE title = 'Jurassic Park')),
((SELECT id FROM users WHERE username = 'frank_thompson'), (SELECT id FROM movies WHERE title = 'Saving Private Ryan')),
((SELECT id FROM users WHERE username = 'frank_thompson'), (SELECT id FROM movies WHERE title = 'The Wolf of Wall Street')),
((SELECT id FROM users WHERE username = 'grace_martin'), (SELECT id FROM movies WHERE title = 'Goodfellas')),
((SELECT id FROM users WHERE username = 'grace_martin'), (SELECT id FROM movies WHERE title = 'Django Unchained')),
((SELECT id FROM users WHERE username = 'grace_martin'), (SELECT id FROM movies WHERE title = 'The Irishman')),
((SELECT id FROM users WHERE username = 'henry_taylor'), (SELECT id FROM movies WHERE title = 'Kill Bill: Vol. 1')),
((SELECT id FROM users WHERE username = 'henry_taylor'), (SELECT id FROM movies WHERE title = 'E.T. the Extra-Terrestrial')),
((SELECT id FROM users WHERE username = 'henry_taylor'), (SELECT id FROM movies WHERE title = 'Terminator 2: Judgment Day'));
