INSERT INTO countries (name, code) VALUES
('Argentina', 'AR'),
('Australia', 'AU'),
('Austria', 'AT'),
('Brazil', 'BR'),
('Canada', 'CA'),
('China', 'CN'),
('Denmark', 'DK'),
('France', 'FR'),
('Germany', 'DE'),
('India', 'IN'),
('Italy', 'IT'),
('Japan', 'JP'),
('Mexico', 'MX'),
('Netherlands', 'NL'),
('Norway', 'NO'),
('South Africa', 'ZA'),
('South Korea', 'KR'),
('Spain', 'ES'),
('Sweden', 'SE'),
('Ukraine', 'UA'),
('United Kingdom', 'GB'),
('United States', 'US');
